"""定数定義モジュール"""

# リアルタイムデータ取得関連
DEFAULT_REALTIME_TTL_SECONDS = 30
DEFAULT_REALTIME_BACKOFF_SECONDS = 1

# ペーパートレード関連
DEFAULT_PAPER_TRADER_REFRESH_INTERVAL = 300
PAPER_TRADER_REALTIME_FALLBACK_DEFAULT = False

# ボラティリティ指標
DEFAULT_VOLATILITY_SYMBOL = "^VIX"
FALLBACK_VOLATILITY_SYMBOLS = ["^VIX", "^VXO"]