"""定数定義モジュール"""

# リアルタイムデータ取得関連
DEFAULT_REALTIME_TTL_SECONDS = 30
DEFAULT_REALTIME_BACKOFF_SECONDS = 1

# ペーパートレード関連
DEFAULT_PAPER_TRADER_REFRESH_INTERVAL = 300
PAPER_TRADER_REALTIME_FALLBACK_DEFAULT = False

# ボラティリティ指標
DEFAULT_VOLATILITY_SYMBOL = "^VIX"
FALLBACK_VOLATILITY_SYMBOLS = ["^VIX", "^VXO"]

# データロード関連
STALE_DATA_MAX_AGE = timedelta(days=2)
MINIMUM_DATA_POINTS = 50
MARKET_SUMMARY_CACHE_KEY = "market_summary_snapshot"
MARKET_SUMMARY_TTL = 1800
FUNDAMENTAL_CACHE_TTL = 86400
CRYPTO_PAIRS = [
    "BTC-USD",
    "ETH-USD",
    "XRP-USD",
]
FX_PAIRS = [
    "USDJPY=X",
    "EURJPY=X",
    "GBPJPY=X",
]
JP_STOCKS = [
    "7203.T",
    "6758.T",
    "9984.T",
]